spring510/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :gradedists
  resources :courses
  resources :syllabuses
  #get 'welcome/homepage'
  get 'slider/index'
  root 'welcome#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'slider/result'
  get 'slider/result'
  post 'courses/addlikes'
end

spring510/app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]


  # GET /courses
  # GET /courses.json
  def index  
    @courses = Course.paginate(:page => params[:page],:per_page => 5)
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @courses = Course.all
    @grades = Gradedist.all
    @post = Post.new
    @thePost = Post.all
    @syllabus = Syllabus.all
  end



  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def course_params
      params.require(:course).permit(:cid, :name, :description, :syllabus)
    end
end

spring510/app/helpers/courses_helper.rb
module CoursesHelper  


end

spring510/app/views/courses/_form.html.erb
<%= form_for(course) do |f| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cid %>
    <%= f.number_field :cid %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :syllabus %>
    <%= f.text_field :syllabus %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spring510/app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

spring510/app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table>
  <thead>
    <tr>
      <th>Cid</th>
      <th>Name</th>
      <th>Description</th>
      <th>Syllabus</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  
</table>

<br>

<%= link_to 'New Course', new_course_path %>


<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>1 Col Portfolio - Start Bootstrap Template</title>

      </head>

      <body>
      <!-- Page Content -->
      <div class="container">

        <!-- Page Heading -->
        <div class="row">
          <div class="col-lg-12">
            <h1 class="page-header">Page Heading
              <small>Secondary Text</small>
            </h1>
          </div>
        </div>
        <!-- /.row -->

        <!-- Project One -->
        <tbody>
          <% @courses.each do |course| %>
          <div class="row">
            <div class="col-md-7">

              <%=
              #if FileTest.exist?("#{Rails.root}/app/assets/images/#{course.imgpath}")
              #  image_tag(course.imgpath , :class =>"img-responsive")
              #else
                image_tag('http://placehold.it/700x300' , :class =>"img-responsive")
              #end
              %>

              <!--<img class="img-responsive" src="http://placehold.it/700x300" alt="">-->

            </div>
            <div class="col-md-5">
              <%= link_to course,:style=> 'color: black;' do%> 
              
                <h3><%= course.cid %></h3>
                <h4><%= course.name %></h4>
              
              <%end%>
              <p><%= course.description %></p>
            </div>
          </div>
          <td><%= course.syllabus %></td>
          <td><%= link_to 'Show', course %></td>
          <td><%= link_to 'Edit', edit_course_path(course) %></td>
          <td><%= link_to 'Destroy', course, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
        <% end %>
      </tbody>

      <!-- /.row -->

      <hr>

      <!-- Pagination -->
      <%= will_paginate @courses, renderer: BootstrapPagination::Rails%>

      <!-- /.row -->

      <hr>

      <!-- Footer -->
      <footer>
        <div class="row">
          <div class="col-lg-12">
            <p>Copyright &copy; Your Website 2014</p>
          </div>
        </div>
        <!-- /.row -->
      </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

  </body>

  </html>

spring510/app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

spring510/app/views/courses/show.html.erb
<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Blog Post - Start Bootstrap Template</title>

    <!-- Custom CSS -->
    <link href="css/blog-post.css" rel="stylesheet">
    <link href="#{Rails.root}public/data_table.css" rel="stylesheet">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->



    </head>

    <body>
        <!-- Page Content -->
        <div class="container">

            <div class="row">

                <!-- Blog Post Content Column -->
                <div class="col-lg-8">

                    <!-- Blog Post -->

                    <!-- Title -->
                    <h1><%= @course.name %></h1>

                    <!-- Author -->
                    <p class="lead">
                     <%= @course.cid %>
                 </p>

                 <hr>

                <!-- Date/Time 
                <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>

                <hr>-->

                <!-- Preview Image -->
                <%=
                #if FileTest.exist?("#{Rails.root}/app/assets/images/#{@course.imgpath}")
                  #  image_tag(@course.imgpath , :class =>"img-responsive")
                #else
                image_tag('http://placehold.it/700x300' , :class =>"img-responsive")
                #end
                %>
                <hr>

                <!-- Post Content -->
                <p class="lead"><%= @course.description %></p>


                <table class="table-fill">
                    <thead>
                        <tr>
                            <th class="text-left">Semester</th>
                            <th class="text-left">Professor</th>
                            <th class="text-left">A's</th>
                            <th class="text-left">Total</th>
                            <th class="text-left">A%</th>
                        </tr>
                    </thead>
                    <tbody class="table-hover">
                        <% @grades.select{|g| g.cid == @course.cid}.each do |g|%>
                        <tr>
                            <td class="text-left"><%=g.semester%></td>
                            <td class="text-left"><%= (g.instructor).split(',')[0]  %></td>
                            <td class="text-left"><%=g.a%></td>
                            <td class="text-left"><%=g.total%></td>
                            <td class="text-left"><%= (g.a*100)/g.total %>%</td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
                <hr>
                <!-- Blog Comments -->


                <h2>Syllabus<h2>
                <table class="table-fill">
                    <thead>
                        <tr>
                            <th class="text-left">Semester</th>
                            <th class="text-left">Professor</th>
                            <th class="text-left">Link</th>
                        </tr>
                    </thead>
                    <tbody class="table-hover">
                        <% @syllabus.select{|g| g.cid == @course.cid}.each do |g|%>
                        <tr>
                            <td class="text-left"><%=g.semester%></td>
                            <td class="text-left"><%= g.prof %></td>
                            <td class="text-left"><a href="http://<%= g.link %>"><%= g.link %></a></td>
                        </tr>
                        <%end%>
                    </tbody>
                </table>
                <hr>

                <%= link_to "Upload syallbus" , new_syllabus_path %>



                <!-- Comments Form -->
                <hr>

                <!-- Posted Comments -->
                <%= @course.cid %>
                <%= form_for @post, :url => posts_path, :html => {:method => :post} do |f| %>
                <div class="well">
                  <h4>PICK a nickname:</h4>
                  <div class="form-group">
                      <%= f.text_field :user , class: "form-control",  rows: "3"%>
                  </div>
                  <h4>Leave a Comment:</h4>
                  <div class="form-group">
                      <%= f.text_area :content , class: "form-control",  rows: "3"%>
                  </div>   
                  <%= f.hidden_field :cid, value: @course.cid %>
                  <%= f.submit "Add New Comment", class: "btn btn-primary" %>
              </div>
              <% end %>

              <!-- Comment -->
              


                <% @thePost.select{|g| g.cid == @course.cid}.each do |g|%>
                <div class="media">
                 <!-- <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>-->
                <div class="media-body">
                <h4 class="media-heading"><%=g.user%>
                        <small><%=g.created_at%></small>
                    </h4>
                    <%=g.content%>
                </div>
                </div>
                <%end%>



            

            <!-- Comment 

            <div class="media">
                <a class="pull-left" href="#">
                    <img class="media-object" src="http://placehold.it/64x64" alt="">
                </a>
                <div class="media-body">
                    <h4 class="media-heading">Start Bootstrap
                        <small>August 25, 2014 at 9:30 PM</small>
                    </h4>
                    Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.-->
                    <!-- Nested Comment 
                    <div class="media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="http://placehold.it/64x64" alt="">
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading">Nested Start Bootstrap
                                <small>August 25, 2014 at 9:30 PM</small>
                            </h4>
                            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
                        </div>
                    </div>
                   
                </div>
            </div>
            -->
             <!-- End Nested Comment -->

        </div>

        <!-- Blog Sidebar Widgets Column -->
        <div class="col-md-4">

                <!-- Blog Search Well 
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                </div>-->

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Courses</h4>
                    <div class="row">
                        <div class="col-md-16">
                           <% @courses.each do |c| %>
                           <ul class="list-unstyled">
                            <li><%= link_to c.name, c %></li>     
                        </ul>
                        <%end%>
                    </div>

                </div>
                <!-- /.row -->
            </div>

                <!-- Side Widget Well 
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>-->

            </div>

        </div>
        <!-- /.row -->

        <hr>

        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Your Website 2014</p>
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <!-- /.container -->

    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

</body>

</html>