spring510/config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :gradedists
  resources :courses
  resources :syllabuses
  #get 'welcome/homepage'
  get 'slider/index'
  root 'welcome#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  post 'slider/result'
  get 'slider/result'
  post 'courses/addlikes'
end

spring510/app/models/gradedist.rb
class Gradedist < ApplicationRecord
	belongs_to :course
end

spring510/app/controllers/gradedists_controller.rb
class GradedistsController < ApplicationController
  before_action :set_gradedist, only: [:show, :edit, :update, :destroy]

  # GET /gradedists
  # GET /gradedists.json
  def index
    @distByCourse = Gradedist.group(:cid).select("cid, SUM(gradedists.a) AS a, SUM(gradedists.bs) AS bs, SUM(gradedists.cs) AS cs, SUM(gradedists.total) AS total")

    @distByInstructor = Gradedist.group(:instructor).select("instructor, SUM(gradedists.a) AS a, SUM(gradedists.bs) AS bs, SUM(gradedists.cs) AS cs, SUM(gradedists.total) AS total")
  end

  # GET /gradedists/1
  # GET /gradedists/1.json
  def show
  end

  # GET /gradedists/new
  def new
    @gradedist = Gradedist.new
  end

  # GET /gradedists/1/edit
  def edit
  end

  # POST /gradedists
  # POST /gradedists.json
  def create
    @gradedist = Gradedist.new(gradedist_params)

    respond_to do |format|
      if @gradedist.save
        format.html { redirect_to @gradedist, notice: 'Gradedist was successfully created.' }
        format.json { render :show, status: :created, location: @gradedist }
      else
        format.html { render :new }
        format.json { render json: @gradedist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gradedists/1
  # PATCH/PUT /gradedists/1.json
  def update
    respond_to do |format|
      if @gradedist.update(gradedist_params)
        format.html { redirect_to @gradedist, notice: 'Gradedist was successfully updated.' }
        format.json { render :show, status: :ok, location: @gradedist }
      else
        format.html { render :edit }
        format.json { render json: @gradedist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gradedists/1
  # DELETE /gradedists/1.json
  def destroy
    @gradedist.destroy
    respond_to do |format|
      format.html { redirect_to gradedists_url, notice: 'Gradedist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gradedist
      @gradedist = Gradedist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gradedist_params
      params.require(:gradedist).permit(:cid, :section, :instructor, :semester, :integer, :as, :bs, :cs, :ds, :fs, :s, :u, :in, :la, :au, :nr, :w, :total)
    end
end

spring510/app/helpers/gradedists_helper.rb
module GradedistsHelper
end

spring510/app/views/gradedists/_form.html.erb
<%= form_for(gradedist) do |f| %>
  <% if gradedist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gradedist.errors.count, "error") %> prohibited this gradedist from being saved:</h2>

      <ul>
      <% gradedist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :cid %>
    <%= f.number_field :cid %>
  </div>

  <div class="field">
    <%= f.label :section %>
    <%= f.number_field :section %>
  </div>

  <div class="field">
    <%= f.label :instructor %>
    <%= f.text_field :instructor %>
  </div>

  <div class="field">
    <%= f.label :semester %>
    <%= f.text_field :semester %>
  </div>

  <div class="field">
    <%= f.label :as %>
    <%= f.number_field :as %>
  </div>

  <div class="field">
    <%= f.label :bs %>
    <%= f.number_field :bs %>
  </div>

  <div class="field">
    <%= f.label :cs %>
    <%= f.number_field :cs %>
  </div>

  <div class="field">
    <%= f.label :ds %>
    <%= f.number_field :ds %>
  </div>

  <div class="field">
    <%= f.label :fs %>
    <%= f.number_field :fs %>
  </div>

  <div class="field">
    <%= f.label :s %>
    <%= f.number_field :s %>
  </div>

  <div class="field">
    <%= f.label :u %>
    <%= f.number_field :u %>
  </div>

  <div class="field">
    <%= f.label :in %>
    <%= f.number_field :in %>
  </div>

  <div class="field">
    <%= f.label :la %>
    <%= f.number_field :la %>
  </div>

  <div class="field">
    <%= f.label :au %>
    <%= f.number_field :au %>
  </div>

  <div class="field">
    <%= f.label :nr %>
    <%= f.number_field :nr %>
  </div>

  <div class="field">
    <%= f.label :w %>
    <%= f.number_field :w %>
  </div>

  <div class="field">
    <%= f.label :total %>
    <%= f.number_field :total %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

spring510/app/views/gradedists/edit.html.erb
<h1>Editing Gradedist</h1>

<%= render 'form', gradedist: @gradedist %>

<%= link_to 'Show', @gradedist %> |
<%= link_to 'Back', gradedists_path %>

spring510/app/views/gradedists/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Grade Distribution</h1>
<%
def getId(cid)
  id = Course.where(cid: cid).select("id").take
end
%>




<table class=" table table-striped sortable">
  <thead>
    <tr>
      
      <th>Course ID</th>
      <th>A%</th>
      <th>B%</th>
      <th>C%</th>
      <th>Total Enrollment</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%
     i = 0
     @distByCourse.each do |d|
     i += 1
    %>
      <tr>
        
        
        <td><%= 
          if(getId(d.cid)!=nil)
            link_to d.cid, course_path(:id => getId(d.cid).id)
          else
            d.cid
          end
            %> </td>
        <td><%= d.a*100 / d.total %>%</td>
        <td><%= d.bs*100 / d.total %>%</td>
        <td><%= d.cs*100 / d.total %>%</td>
        <td><%= d.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<table class=" table table-striped sortable">
  <thead>
    <tr>
      
      <th>Instructor</th>
      <th>A%</th>
      <th>B%</th>
      <th>C%</th>
      <th>Total Enrollment</th>      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <%
      i = 0 
      @distByInstructor.each do |d| 
      i += 1
    %>
      <tr>
      
        <td><%= d.instructor %></td>
        <td><%= d.a*100 / d.total %>%</td>
        <td><%= d.bs*100 / d.total %>%</td>
        <td><%= d.cs*100 / d.total %>%</td>
        <td><%= d.total %></td>
      </tr>
    <% end %>
  </tbody>
</table>

spring510/app/views/gradedists/new.html.erb
<h1>New Gradedist</h1>

<%= render 'form', gradedist: @gradedist %>

<%= link_to 'Back', gradedists_path %>

spring510/app/views/gradedists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Cid:</strong>
  <%= @gradedist.cid %>
</p>

<p>
  <strong>Section:</strong>
  <%= @gradedist.section %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @gradedist.instructor %>
</p>

<p>
  <strong>Semester:</strong>
  <%= @gradedist.semester %>
</p>

<p>
  <strong>As:</strong>
  <%= @gradedist.as %>
</p>

<p>
  <strong>Bs:</strong>
  <%= @gradedist.bs %>
</p>

<p>
  <strong>Cs:</strong>
  <%= @gradedist.cs %>
</p>

<p>
  <strong>Ds:</strong>
  <%= @gradedist.ds %>
</p>

<p>
  <strong>Fs:</strong>
  <%= @gradedist.fs %>
</p>

<p>
  <strong>S:</strong>
  <%= @gradedist.s %>
</p>

<p>
  <strong>U:</strong>
  <%= @gradedist.u %>
</p>

<p>
  <strong>In:</strong>
  <%= @gradedist.in %>
</p>

<p>
  <strong>La:</strong>
  <%= @gradedist.la %>
</p>

<p>
  <strong>Au:</strong>
  <%= @gradedist.au %>
</p>

<p>
  <strong>Nr:</strong>
  <%= @gradedist.nr %>
</p>

<p>
  <strong>W:</strong>
  <%= @gradedist.w %>
</p>

<p>
  <strong>Total:</strong>
  <%= @gradedist.total %>
</p>

<%= link_to 'Edit', edit_gradedist_path(@gradedist) %> |
<%= link_to 'Back', gradedists_path %>